# Generated by Django 5.0.6 on 2024-05-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SectorActividade',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nif', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=60)),
                ('website', models.URLField(max_length=60)),
                ('descricao', models.TextField(verbose_name=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.endereco')),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.sectoractividade')),
            ],
        ),
    ]
